// Mocks generated by Mockito 5.0.14 from annotations
// in estiminator/test/core/presentation/multiple_reactions_disposer_test.dart.
// Do not manually edit this file.

import 'package:mobx/mobx.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeReaction_0 extends _i1.Fake implements _i2.Reaction {}

/// A class which mocks [ReactionDisposer].
///
/// See the documentation for Mockito's code generation for more information.
class MockReactionDisposer extends _i1.Mock implements _i2.ReactionDisposer {
  MockReactionDisposer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Reaction get reaction => (super.noSuchMethod(Invocation.getter(#reaction),
      returnValue: _FakeReaction_0()) as _i2.Reaction);
  @override
  void call() => super.noSuchMethod(Invocation.method(#call, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
