// Mocks generated by Mockito 5.0.14 from annotations
// in estiminator/test/create_session/presentation/model/scales_state_model_mapper_test.dart.
// Do not manually edit this file.

import 'package:estiminator/core/persentation/strings.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Strings].
///
/// See the documentation for Mockito's code generation for more information.
class MockStrings extends _i1.Mock implements _i2.Strings {
  MockStrings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get(int? id) =>
      (super.noSuchMethod(Invocation.method(#get, [id]), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}
