// Mocks generated by Mockito 5.0.14 from annotations
// in estiminator/test/create_session/domain/use_case/create_session_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:estiminator/create_session/domain/models/create_session_domain_model.dart'
    as _i4;
import 'package:estiminator/create_session/domain/service/create_session_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ICreateSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockICreateSessionService extends _i1.Mock
    implements _i2.ICreateSessionService {
  MockICreateSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createSession(
          _i4.CreateSessionDomainModel? createSessionDomainModel) =>
      (super.noSuchMethod(
          Invocation.method(#createSession, [createSessionDomainModel]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
