// Mocks generated by Mockito 5.0.14 from annotations
// in estiminator/test/create_session/domain/use_case/get_estimation_scales_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:estiminator/create_session/domain/models/estimation_scales_domain_model.dart'
    as _i2;
import 'package:estiminator/create_session/domain/service/estimation_scales_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEstimationScalesDomainModel_0 extends _i1.Fake
    implements _i2.EstimationScalesDomainModel {}

/// A class which mocks [IEstimationScalesRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIEstimationScalesRepo extends _i1.Mock
    implements _i3.IEstimationScalesRepo {
  MockIEstimationScalesRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.EstimationScalesDomainModel> getScales() =>
      (super.noSuchMethod(Invocation.method(#getScales, []),
              returnValue: Future<_i2.EstimationScalesDomainModel>.value(
                  _FakeEstimationScalesDomainModel_0()))
          as _i4.Future<_i2.EstimationScalesDomainModel>);
  @override
  String toString() => super.toString();
}
