// Mocks generated by Mockito 5.0.14 from annotations
// in estiminator/test/core/presentation/input/validation_executor_test.dart.
// Do not manually edit this file.

import 'package:estiminator/core/persentation/input/input.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Input].
///
/// See the documentation for Mockito's code generation for more information.
class MockInput<T> extends _i1.Mock implements _i2.Input<T> {
  MockInput() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T get value =>
      (super.noSuchMethod(Invocation.getter(#value), returnValue: null) as T);
  @override
  void set(T? value) => super.noSuchMethod(Invocation.method(#set, [value]),
      returnValueForMissingStub: null);
  @override
  void validate() => super.noSuchMethod(Invocation.method(#validate, []),
      returnValueForMissingStub: null);
  @override
  void clear() => super.noSuchMethod(Invocation.method(#clear, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
