// Mocks generated by Mockito 5.0.14 from annotations
// in estiminator/test/create_session/presentation/store/mx_create_session_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:estiminator/core/domain/credentials/user_credentials_domain_model.dart'
    as _i4;
import 'package:estiminator/core/domain/credentials/user_credentials_provider.dart'
    as _i10;
import 'package:estiminator/create_session/domain/models/create_session_domain_model.dart'
    as _i8;
import 'package:estiminator/create_session/domain/models/estimation_scales_domain_model.dart'
    as _i3;
import 'package:estiminator/create_session/domain/use_case/create_session_use_case.dart'
    as _i6;
import 'package:estiminator/create_session/domain/use_case/get_estimation_scales_use_case.dart'
    as _i9;
import 'package:estiminator/create_session/presentation/model/estimation_scales_state_model.dart'
    as _i2;
import 'package:estiminator/create_session/presentation/model/scales_state_model_mapper.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEstimationScalesStateModel_0 extends _i1.Fake
    implements _i2.EstimationScalesStateModel {}

class _FakeEstimationScalesDomainModel_1 extends _i1.Fake
    implements _i3.EstimationScalesDomainModel {}

class _FakeUserCredentialsDomainModel_2 extends _i1.Fake
    implements _i4.UserCredentialsDomainModel {}

/// A class which mocks [EstimationScalesStateModelMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockEstimationScalesStateModelMapper extends _i1.Mock
    implements _i5.EstimationScalesStateModelMapper {
  MockEstimationScalesStateModelMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EstimationScalesStateModel map(_i3.EstimationScalesDomainModel? input) =>
      (super.noSuchMethod(Invocation.method(#map, [input]),
              returnValue: _FakeEstimationScalesStateModel_0())
          as _i2.EstimationScalesStateModel);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CreateSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateSessionUseCase extends _i1.Mock
    implements _i6.CreateSessionUseCase {
  MockCreateSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> createSession(
          _i8.CreateSessionDomainModel? createSessionDomainModel) =>
      (super.noSuchMethod(
          Invocation.method(#createSession, [createSessionDomainModel]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetEstimationScalesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetEstimationScalesUseCase extends _i1.Mock
    implements _i9.GetEstimationScalesUseCase {
  MockGetEstimationScalesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.EstimationScalesDomainModel> getScales() =>
      (super.noSuchMethod(Invocation.method(#getScales, []),
              returnValue: Future<_i3.EstimationScalesDomainModel>.value(
                  _FakeEstimationScalesDomainModel_1()))
          as _i7.Future<_i3.EstimationScalesDomainModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [IUserCredentialsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserCredentialsProvider extends _i1.Mock
    implements _i10.IUserCredentialsProvider {
  MockIUserCredentialsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.UserCredentialsDomainModel> getUserCredentials() =>
      (super.noSuchMethod(Invocation.method(#getUserCredentials, []),
              returnValue: Future<_i4.UserCredentialsDomainModel>.value(
                  _FakeUserCredentialsDomainModel_2()))
          as _i7.Future<_i4.UserCredentialsDomainModel>);
  @override
  _i7.Future<void> setUid(String? uId) =>
      (super.noSuchMethod(Invocation.method(#setUid, [uId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  String toString() => super.toString();
}
